config/routes.rb
LeaveSystem::Application.routes.draw do
 
match '/employees/get_emp_manager_name/:id' => 'employees#get_emp_manager_name' 

match '/employees/emp_leave_status' => 'employees#emp_leave_status'

match '/articles/:id/save_comment' => 'articles#save_comment'

match '/employees/employee_separation' => 'employees#employee_separation' 
match '/leave_credits/:id/ohupdate' => 'leave_credits#ohupdate'

resource :authentication, :controller => "authentication" do
  member do
     match :login
     get :logout
     match :set_password
     match :forgot_password
     match :reset_password
  end
end

resources :holidays, :controller => 'holidays' do
  member do
      post 'destroy/id', :action => :destroy
  end
end

resources :employees, :controller => "employees" do
   member do
       put :update
       get :leave_balances
       get :my_leave_approvals
       get :my_leaves
       get :team_leaves   
	get :anew, :action => :anew
post :acreate, :action => :acreate
       post 'destroy/id', :action => :destroy
   end

   resources :leaves, :controller => "leaves" do
    member do

	post :update
       get :request_details
       post :action_leave
       get :quarterly_credits
    end

   end
end

resources :articles do
member do

post 'aindex', :action => :aindex
get 'anew/id', :action => :anew
post 'acreate/id', :action => :acreate
end
end 

resources :leaves, :controller => "leave_credits" do

    collection do
get :ohindex
get :ohnew
post :ohcreate
get :ohedit
       get :show
       get :quarterly_credits
       post :rt_qlc
       get :annual_credits
       post :rt_alc
    end
end

end

app/models/employee.rb
require 'role_access'

class Employee < ActiveRecord::Base
include RoleAccess
  attr_accessible :local_addr, :perm_addr, :age, :designation, :dob, :doj, :emp_id, :first_name, :last_name, :manager_emp_id, :manager_name, :mob_no, :off_email_id, :pan_no, :pers_email_id, :phone_no, :gender, :seperation_date, :encashed_days, :roles
attr_accessible :leaves_attributes, :roles, :leave_attributes

#attr_protected :roles

validate :dates_cannot_be_in_the_future
validates_presence_of :local_addr, :message => "Local address cannot be blank"
validates_presence_of :perm_addr, :message => "Permanent address cannot be blank"
validates_presence_of :age, :message => "Unable to calculate employee's age at joining; please enter employee dob correctly.."
validates_presence_of :designation, :message => "Employee's designation at RapidThink cannot be blank"
validates_presence_of :dob, :message => "Employee's date of birth cannot be blank"
validates_presence_of :doj, :message => "Employee's date of joining RapidThink cannot be blank"
validates_presence_of :emp_id, :message => "Emp Id cannot be blank"
validates_presence_of :first_name, :message => "Employee's first name cannot be blank"
validates_presence_of :last_name, :message => "Employee's last name cannot be blank"
validates_presence_of :manager_emp_id, :message => "Employee's manager id cannot be blank"
validates_presence_of :manager_name, :message => "Employee's manager name cannot be blank"
validates_presence_of :mob_no, :message => "Employee's mobile number cannot be blank"
validates_presence_of :off_email_id, :message => "Employee's RapidThink email id cannot be blank"
validates_presence_of :pan_no, :message => "Employee's PAN number cannot be blank"
validates_presence_of :pers_email_id, :message => "Employee's personal email id cannot be blank"
validates_presence_of :phone_no, :message => "Employee's permanent phone no cannot be blank"
validates_presence_of :roles, :message => "Employee roles cannot be blank"
validates_presence_of :gender, :message => "Employee gender cannot be blank"

validates_uniqueness_of :emp_id, :message => "Employee id has to be unique, this emp id already exists!"
validates_uniqueness_of :mob_no, :message => "Employee mobile no has to be unique"
validates_uniqueness_of :pan_no, :message => "Employee PAN NO has to be unique"
validates_uniqueness_of :off_email_id, :message => "Employee's RapidThink email id should be unique"
validates_uniqueness_of :pers_email_id, :message => "Employee's personal email id should be unique"

validates_date :dob, :invalid_date_message => "Please enter a valid date for employee's date of birth"
validates_date :doj, :invalid_date_message => "Please enter a valid date for employee's date of joining RapidThink"


validates_length_of :mob_no, :is => 10, :message => "Mobile number entry should contain 10 digits"

validates_numericality_of :age, :only_integer => true, :greater_than_or_equal_to => 18, :message => "Employee should be greater than 18 years of age"
validates_numericality_of :emp_id, :only_integer => true,:greater_than_or_equal_to => 0, :message => "Please enter a positive integer for emp id"
validates_numericality_of :manager_emp_id, :only_integer => true,:greater_than_or_equal_to => 0, :message => "Please enter a positive integer for manager emp id"
validates_numericality_of :mob_no, :only_integer => true, :greater_than_or_equal_to => 0, :message => "Please enter a valid numerical value for employee's mobile no"
validates_numericality_of :phone_no, :only_integer => true, :greater_than_or_equal_to => 0, :message => " Please enter a valid numerical value for employee's phone no"


validates_format_of :off_email_id,
                      :with => /^([^@\s]+)@((?:[-a-zA-Z0-9]+\.)+[a-zA-Z]{2,})$/,
                      :message => 'Employee\'s official email id must have a valid format, e.g. a@b.com'

validates_format_of :pers_email_id,
                      :with => /^([^@\s]+)@((?:[-a-zA-Z0-9]+\.)+[a-zA-Z]{2,})$/,
                      :message => 'Employee\' personal email id must have a valid format, e.g. a@b.com'


has_many :leaves, :class_name => 'Leave', :foreign_key => 'employee_id'
has_many :articles, :class_name => 'Article', :foreign_key => 'employee_id'
has_one :user, :dependent => :destroy
has_many :subordinates, :class_name => "Employee", :foreign_key => "manager_emp_id"
belongs_to :manager, :class_name => "Employee"

accepts_nested_attributes_for :leaves

def self.search(search)
   if search
    if search.is_a?(String)
       where('emp_id LIKE ? or last_name LIKE ? or first_name LIKE ? or designation LIKE ?', "%#{search}%" , "%#{search}%" , "%#{search}%", "%#{search}%")
    end
@salaryst=Employee.where("id=?", @salary.empid).pluck(:empid)[0]
   else
       scoped
   end
end


def dates_cannot_be_in_the_future
       errors.add(:doj,"Joining date cannot be in the future") if 
       (!doj.blank? and doj > Date.today) 
       errors.add(:dob,"Date of birth cannot be in the future") if
       (!dob.blank? and dob > Date.today)
end

def find_leave_approver
emp=self
    while (1) do
          if emp.manager.is_leave_approver?
              manager=emp.manager
              ActiveRecord::Base.logger.info("The manager now is: #{manager.last_name}, #{manager.emp_id}")
              return manager
           else
              emp=emp.manager
          end
    end
end

def reportees
manager=self
@reportees=Array.new
   find_reportees(manager.emp_id)
end

def find_reportees(emp_id)
      rep = Employee.find_all_by_manager_emp_id(emp_id)
      for i in 0..rep.count-1
      	@reportees << rep[i]
      	find_reportees(rep[i].emp_id)
      end
      @reportees
end

def manager
    Employee.find_by_emp_id(self.manager_emp_id)
end

def is_manager?
    ["Manager","SSE","Senior Manager"].include? self.designation
end

end

app/controllers/employees_controller.rb
require 'will_paginate/array'
class EmployeesController < ApplicationController
include Utilities
layout 'employee'


before_filter :login_required
before_filter :find_logged_emp
before_filter :find_user_id

 def new
    @employee=Employee.new
    @user=User.new
	@employee.leaves.build
	
 end

 def index
     if @emp.is_admin?
     #@employees=Employee.all.paginate(:page => params[:page], :per_page => 5)
        @employees=Employee.search(params[:search]).paginate(:page => params[:page], :per_page => 5)
    # Rails.logger.info("hihello the employee id is: #{@employee.requester_emp_id}")
     else
     @my_reportees=@emp.reportees
     Rails.logger.info ("I have #{@my_reportees.count} number of reportees!!")
     @employees=Array.new
     @tmp = 0
     for i in 0..@my_reportees.count-1	
         @tmp=Employee.find(:all,:conditions =>['emp_id=?', @my_reportees[i].emp_id])
          for j in 0..@tmp.count-1
            @employees<<@tmp[j]
          end

end
@employees = @employees.paginate(:page => params[:page], :per_page => 5)  

end
    end

  def create
     @employee=Employee.new
     @user=User.new
     @user.login=params[:employee][:emp_id]
     @user.email=params[:employee][:off_email_id]
     @employee=Employee.new(params[:employee])
     params[:employee][:roles].delete("") 
     if !params[:employee][:roles].empty?
        tmproles=params[:employee][:roles]
     else
        tmproles=[].push(Role::None.id)
     end
     @employee.roles = Role.find_all(*tmproles.map(&:to_i))
     @employee.age=@employee.doj.year-@employee.dob.year
     @user.employee=@employee
     Rails.logger.info("The mob no is: #{@employee.mob_no}")

       if @employee.save && @user.save 

         flash[:notice] = "New employee with emp id: #{@employee.emp_id} was successfully created!"
         Notifications.welcome(@user).deliver
         redirect_to employee_path(@employee)
       else
          Rails.logger.info("The errors are: #{@employee.errors.full_messages}")
          flash[:errors]=(@employee.errors)
          #redirect_to new_employee_path
          render :action => "new"
      end
  end
 
 
  def leave_balances

        @leavecredit_sl = Leave.find(:all, :conditions => {:requester_emp_id => @emp.emp_id, :leave_type => "SL", :status => "Credit"}, :select => "SUM(no_of_days) AS no_of_days", :group => { :requester_emp_id => @emp.emp_id})
	@leavedebit_sl = Leave.find(:all, :conditions => {:requester_emp_id => @emp.emp_id, :leave_type => "SL", 
             :status => "Approved"}, :select => "SUM(no_of_days) AS no_of_days", :group => { :requester_emp_id => @emp.emp_id})

	@leavecredit_cl = Leave.find(:all, :conditions => {:requester_emp_id => @emp.emp_id, :leave_type => "CL",
             :status => "Credit"}, :select => "SUM(no_of_days) AS no_of_days", :group => { :requester_emp_id => @emp.emp_id})
	@leavedebit_cl = Leave.find(:all, :conditions => {:requester_emp_id => @emp.emp_id, :leave_type => "CL", 
             :status => "Approved"}, :select => "SUM(no_of_days) AS no_of_days", :group => { :requester_emp_id => @emp.emp_id})

	@leavecredit_el = Leave.find(:all, :conditions => {:requester_emp_id => @emp.emp_id, :leave_type => "EL", 
             :status => "Credit"}, :select => "SUM(no_of_days) AS no_of_days", :group => { :requester_emp_id => @emp.emp_id})
	@leavedebit_el = Leave.find(:all, :conditions => {:requester_emp_id => @emp.emp_id, :leave_type => "EL", 
             :status => "Approved"}, :select => "SUM(no_of_days) AS no_of_days", :group => { :requester_emp_id => @emp.emp_id})
 x = Time.now.year
 	 a= Date.new(x)
	
	 z = x + 1
	 b = Date.new(x).change(:year => z) -1
	@leavecredit_oh = Leave.find(:all, :conditions => {:requester_emp_id => @emp.emp_id, :leave_type => "OH", :status => "Credit", :start_date => a..b }, :select => "SUM(no_of_days) AS no_of_days", :group => { :requester_emp_id => @emp.emp_id})
	 b = Date.new(x).change(:year => z) 
	

	@leavedebit_oh = Leave.find(:all, :conditions => {:requester_emp_id => @emp.emp_id, :leave_type => "OH", :status => "Approved", :start_date => a..b }, :select => "SUM(no_of_days) AS no_of_days", :group => { :requester_emp_id => @emp.emp_id})
	
if @emp.emp_id != '0001' && @emp.emp_id != '0002' 

	if @leavecredit_sl == []&& @leavedebit_sl == []
	  @sickleavebal  = 0
        elsif @leavedebit_sl == []
	  @sickleavebal = @leavecredit_sl[0].no_of_days
	else
          @sickleavebal = @leavecredit_sl[0].no_of_days  - @leavedebit_sl[0].no_of_days
	end
	
	if@leavecredit_cl == []&& @leavedebit_cl == []
	  @casualleavebal  = 0
  	elsif @leavedebit_cl == []
          @casualleavebal = @leavecredit_cl[0].no_of_days
	else
          @casualleavebal = @leavecredit_cl[0].no_of_days - @leavedebit_cl[0].no_of_days
	end

	if@leavecredit_el == []&& @leavedebit_el == []
	  @earnedleavebal  = 0
  	elsif @leavedebit_el == []
	   @earnedleavebal = @leavecredit_el[0].no_of_days
	else
           @earnedleavebal = @leavecredit_el[0].no_of_days - @leavedebit_el[0].no_of_days
	end
	
      if@leavecredit_oh == [] && @leavedebit_oh == [] 
           @optionalholidaybal = 0
        elsif @leavedebit_oh == [] 
	   @optionalholidaybal = @leavecredit_oh[0].no_of_days 
	else
           @optionalholidaybal = @leavecredit_oh[0].no_of_days - @leavedebit_oh[0].no_of_days
	end

        @totalleavebal =  @sickleavebal + @casualleavebal + @earnedleavebal + @optionalholidaybal
else
  @sickleavebal = 0
 @casualleavebal = 0
  @earnedleavebal = 0
 @optionalholidaybal = 0
@totalleavebal = @sickleavebal + @casualleavebal + @earnedleavebal + @optionalholidaybal
  end
end


  def show
       @employee=Employee.find(params[:id])
       Rails.logger.info("This employees gender is :#{@employee.gender}")
       render :action => 'show', :layout => '/layouts/employee'
  end

     def emp_leave_status
     @employees=Employee.search(params[:search]).paginate(:page => params[:page], :per_page => 5)
     end

  def edit
     @employee=Employee.find(params[:id])
      @employee.leaves.where('admin_comments=?','Initial Credit').build
  end

  def update
     @employee=Employee.find(params[:id])
     
     params[:employee][:roles].delete("") 
     if !params[:employee][:roles].empty?
        tmproles=params[:employee][:roles]
     else
        tmproles=[].push(Role::None.id)
     end
     
     @a = Employee.where('emp_id=?', @employee.emp_id).pluck(:seperation_date)
if @a == [nil]
     @employee.update_attributes(params[:employee])
     @employee.roles = Role.find_all(*tmproles.map(&:to_i))
     @employee.age=@employee.doj.year-@employee.dob.year

     if @employee.save
         Rails.logger.info("The updated mob no is: #{@employee.mob_no}")
         flash[:notice] = "Employee with emp id: #{@employee.emp_id} was successfully updated!"
         redirect_to employee_path(@employee)
     else
         flash[:errors]=@employee.errors
         Rails.logger.info("The errors in update are: #{@employee.errors.each{|i,j| j}}")
         #redirect_to new_employee_path
         render :action => "edit"
     end
       else
         flash[:notice] = "Employee with emp id: #{@employee.emp_id} separated, you cann't edit"
         render :action => "edit"
end
 end


  def my_leave_approvals
    @my_reportees=@emp.reportees
     Rails.logger.info ("I have #{@my_reportees.count} number of reportees!!")
     @employees=Array.new
     @tmp = 0
     for i in 0..@my_reportees.count-1	
         @tmp=Employee.find(:all,:conditions =>['emp_id=?', @my_reportees[i].emp_id])
          for j in 0..@tmp.count-1
            @employees<<@tmp[j]
          end
     end
     @employees

    if Leave.search_leaves(params[:search])!= 'NULL'
	@leaves = []
 	for i in 0..@my_reportees.count-1
	@leave=Leave.search_leaves(params[:search]).where('status!=? AND status=? AND requester_emp_id=?', 'Credit','New', @my_reportees[i].emp_id).order('request_date desc')
 	 @leaves = @leaves+@leave
	end
    end
   @leaves = @leaves.paginate(:page => params[:page], :per_page => 5)    
end

def employee_separation
        @employees=Employee.search(params[:search]).paginate(:page => params[:page], :per_page => 5)
     #@employees=Employee.all.paginate(:page => params[:page], :per_page => 5)
    # Rails.logger.info("hihello the employee id is: #{@employee.requester_emp_id}")
end

 def anew
      @employee=Employee.find(params[:id])
end
def acreate
        @employee=Employee.find(params[:id])
	if  @employee.update_attributes(params[:employee])
          @eldays = @employee.encashed_days
	  @leaves = Leave.create(:start_date => Date.today, :end_date => Date.today, :requester_emp_id => @employee.emp_id, :leave_type => 'EL', :no_of_days =>@eldays, :status => 'Approved', :request_date => Date.today, :admin_comments => 'Employee Separated' )
	  @leaves.save
         flash[:notice] = "Employee with emp id: #{@employee.emp_id} was successfully Separated!"
      redirect_to employees_employee_separation_path
    end
end


  def team_leaves
     @my_reportees=@emp.reportees
     Rails.logger.info ("I have #{@my_reportees.count} number of reportees!!")
     @employees=Array.new
     @tmp = 0
     for i in 0..@my_reportees.count-1	
         @tmp=Employee.find(:all,:conditions =>['emp_id=?', @my_reportees[i].emp_id])
          for j in 0..@tmp.count-1
            @employees<<@tmp[j]
          end
     end
     @employees

    if Leave.search_leaves(params[:search])!= 'NULL'
	@leaves = []
 	for i in 0..@my_reportees.count-1
	@leave=Leave.search_leaves(params[:search]).where('status!=? AND status!=? AND requester_emp_id=?', 'Credit','New', @my_reportees[i].emp_id).order('request_date desc')
 	 @leaves = @leaves+@leave
	end
    end
   @leaves = @leaves.paginate(:page => params[:page], :per_page => 5)
end

  def my_leaves
     @leaves=Leave.where('requester_emp_id=? AND status!=?',current_emp.emp_id,"Credit" ).order('request_date desc').to_a.paginate(:page => params[:page], :per_page => 5)
  end

  def get_emp_manager_name
      emp_manager_emp_id=params[:id]

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_anew_employee_details.html.erb
<%= form_for :employee, :url => {:action => 'acreate'}, :html => {:class => ""} do |f| -%>
  <label for="employee_encashed_date">Separation date</label>
  <%= f.date_select :seperation_date, :default => Date.today, :order => [:day, :month, :year], :use_short_month => true %><br/><br/>

  <label for="leave_type">Encashed EL</label>
  <%=f.text_field :encashed_days, :size=>'15' %> <br/><br/>


<div class="submit">
   <%= f.submit 'Emp separation', :confirm => 'Are you sure to separate this employee ?',  :class => 'leave_button' %>
</div>
<% end %>

app/views/employees/_emp_home.html.erb
<% content_for(:page_heading, "Employee Home") -%>
<% content_for :emp_home do -%>
<div id="useful_links">
  <ul id="my_leaves">My Leaves
  	<%= content_tag('li',link_to("Balances",leave_balances_employee_path(@emp.id)), :class => 'contentblock')%>
	<%= content_tag('li',link_to("History",my_leaves_employee_path(@emp.id)), :class => 'contentblock')%>
	<%= content_tag('li',link_to("New Request",new_employee_leafe_path(@emp.id)), :class => 'contentblock')%>
	<% if @emp.is_leave_approver? %>
	    <%= content_tag('li',link_to("Approvals",my_leave_approvals_employee_path(@emp.emp_id)), :class => 'contentblock')%>
	    <%= content_tag('li',link_to("Team History ",team_leaves_employee_path(@emp.emp_id)), :class => 'contentblock')%>
	<% end %>
  </ul>
  <ul id="my_hols">Holidays <%=Date.today.year%>
        <%= content_tag('li',link_to("Holiday List",holidays_path), :class => 'contentblock')%>
        <% if @emp.is_admin?%>
           <%= content_tag('li',link_to("New Holiday",new_holiday_path), :class => 'contentblock') if @emp.is_admin? %>
           <%= content_tag('li',link_to("Allowed OH", ohindex_leaves_path), :class => 'contentblock') if @emp.is_admin? %>
           <%#= content_tag('li',link_to("New Holiday"), :class => 'contentblock') if @emp.is_admin? %>
        <% end %>
  </ul>
 
  <% if @emp.is_admin?%>
   <ul id="leave_credits">Leave Credits
     <%= content_tag('li',link_to("Quarterly",quarterly_credits_leaves_path))%>
     <%= content_tag('li',link_to("Annual",annual_credits_leaves_path))%>
   </ul>
  <% end %>
 
<% if (@emp.is_leave_approver? or @emp.is_manager? or @emp.is_admin?)  %>
<ul id="emp_dtl_links">RT Employees
   <% if @emp.is_admin?%>
    <%= content_tag('li',link_to("Add ",new_employee_path))%>
    <%= content_tag('li',link_to("View ",employees_emp_leave_status_path))%>
    <%= content_tag('li',link_to("Separation", employees_employee_separation_path))%>
  <% end %>
<% if @emp.is_admin?%>
    <%= content_tag('li',link_to("Modify ",employees_path))%>

<% else %>
    <%= content_tag('li',link_to("View ",employees_path))%>
<% end %>
</ul>
<% end %>

<ul id="emp_blogs_links">Blogs
    <%= content_tag('li',link_to("New Blog",new_article_path))%>
    <%= content_tag('li',link_to("RT Blogs",articles_path))%>
</ul>
</div>
<% end %>

<%= render :file => 'layouts/_emp_hub' %>

app/views/employees/_emp_leave_status_employee.html.erb
<%= content_for(:page_title, " Employee") -%>
<% content_for :emp_sel do %>
<div id="rt_emps">
<h3>Employee Information</h3>
<div id="emp_search">
<%= form_tag employees_emp_leave_status_path, :method => 'get' do %> 
    <%= text_field_tag :search, params[:search], :class => 'search_input' %>
    <input type="submit" value="Search", class="search_button"> <br/><br/>
<% end %>
</div>

</div>
<% end %>

app/views/employees/_emp_separte_details.html.erb
<%= content_for(:page_title, " Employee") -%>
<% content_for :emp_sel do %>
<div id="rt_emps">
<h3>Employee Separation Details</h3>
<div id="emp_search">
<%= form_tag employees_emp_leave_status_path, :method => 'get' do %> 
    <%= text_field_tag :search, params[:search], :class => 'search_input' %>
    <input type="submit" value="Search", class="search_button"> <br/><br/>
<% end %>
</div>

</div>
<% end %>

app/views/employees/_employees.html.erb
<% if employees.is_admin? %>
<table id="rt_employees">
    <tbody>
         <tr>
             <th>Emp id</th>
             <th>Emp Name</th>
             <th>DOB</th>
             <th>Date of Joining</th>
             <th>Designation</th>
             <th>Manager</th>
         </tr>
     <% @employees.each do |emp| %>
         <tr id="emp_<%=emp.emp_id%>">
           <td><%= link_to emp.emp_id, edit_employee_path(emp) %></td>
           <td><%=emp.first_name%></td>
           <td><%=emp.dob.strftime("%d-%b")%></td>
           <td><%=emp.doj.strftime("%d-%b-%Y")%></td>
           <td><%=emp.designation%></td>
           <td><%=emp.manager_name %></td>
        </tr>
     <% end %>
   </tbody>
</table>

<% else %>

<table id="rt_employees">
    <tbody>
         <tr>
             <th>Emp id</th>
            <th>Emp Name</th>
             <th>DOB</th>
             <th>Date of Joining</th>
             <th>Designation</th>
             <th>Manager</th>
         </tr>
     <% @employees.each do |emp| %>
         <tr id="emp_<%=emp.emp_id%>">
           <td><%=link_to emp.emp_id, employee_path(emp)%></td>
            <td><%=emp.first_name%></td>
           <td><%=emp.dob.strftime("%d-%b")%></td>
           <td><%=emp.doj.strftime("%d-%b-%Y")%></td>
           <td><%=emp.designation%></td>
           <td><%=emp.manager_name %></td>
        </tr>
     <% end %>
   </tbody>
</table>

<% end %>


            
 

app/views/employees/anew.html.erb
<% content_for(:page_title, "Edit Employee details") %>
<% content_for :emp_sel do %>

<% if @employee.seperation_date == nil %>

<h3> <%= @employee.first_name+' '+@employee.last_name %> </h3>
<div id="emp_det">
  <%= render "anew_employee_details" %>
</div>
<% else %>
<h3> <%= @employee.first_name+' '+@employee.last_name %> has already separated</h3>
<% end %>
<% end %>

app/views/employees/index.html.erb
<% content_for(:page_title, "View Employees") -%>
<% content_for :emp_sel do %>
<div id="rt_emps">
<% if @emp.is_admin? %>
<h3>Edit Employees</h3>
<div id="emp_search">
<%= form_tag employees_path, :method => 'get' do %> 
    <%= text_field_tag :search, params[:search], :class => 'search_input' %>
    <input type="submit" value="Search", class="search_button"> <br/><br/>
<% end %>
</div>
<%= render :partial => "employees", :object => @emp %>
<%= will_paginate @employees %>
<% else %>
<h3>My Team</h3>
<%= render :partial => "employees", :object => @emp %>
<%= will_paginate @employees %>
<% end %>
</div>
<% end %>

app/views/employees/my_leave_approvals.html.erb
<% content_for(:page_title, "My Leave Approvals") %>
<% content_for :emp_sel do %>

  <h3>Leave Requests For Approval</h3>

<div id="emp_search_appr">

<%= form_tag my_leave_approvals_employee_path, :method => 'get' do %>

<%= select_tag :search, options_for_select(@employees.collect {|p| [p.first_name+" "+p.last_name]}.insert(0,"select all")), {:class => 'emp_lve_select'} %>

<%#= select_tag :search_user, options_for_select(@users.collect{ |user| [user.name, user.id] }.insert(0,"Everyone")), :class => 'submittable'%>
<%#= f.select(:priority, options_for_select({"Stat" => "1", "Urgent" => "2", "Regular" => "3", "Safety" => "4"}, @servicerequest.priority), :prompt => "Choose") %>

    <%#= collection_select(:city, :country_id, @countries, :id, :country_name, {:prompt => false}) %> 
  <%#= f.collection_select :provider_id, Provider.order(:name),:id,:name, include_blank: true %>
 <input type="submit" value="Search", class="search_button"> <br/><br/>
<% end %>
</div>

<div id="leave_reqs">
   <% if @leaves.count > 0 %>
      <%=render "leave_requests"%>
   <% else %>
      <span id="nlfma">There are currently no leave requests for your approval<span>
   <% end %>
</div>
 <%= will_paginate @leaves %>
<% end %>
  


<%#= select_tag :search, "employee_id", Employee.all.collect {|p| [ p.first_name, p.emp_id ] }, params[:search] %>
    <%#= text_field_tag :search, params[:search], :class => 'search_input' %>

app/views/employees/team_leaves.html.erb
<% content_for(:page_title, "My Leave History") %>
<% content_for :emp_sel do %>
<div id="my_leaves">
  <h3> Team Leave History</h3>

<div id="emp_search_history">
<%= form_tag team_leaves_employee_path, :method => 'get' do  %>
<% if @emp.emp_id == '0002'%>
<%= select_tag :search, options_for_select(Employee.all.collect {|p| [p.first_name+" "+p.last_name]}.insert(0,"select all"), params[:search]), {:class => 'emp_lve_select'} %>
<% else %>
<%= select_tag :search, options_for_select(@employees.collect {|p| [p.first_name+" "+p.last_name]}.insert(0,"select all")), {:class => 'emp_lve_select'} %>
<% end %>
 <input type="submit" value="Search", class="search_button"> <br/><br/>
<% end %>
</div>

<div id="my_leave_reqs">
   <%=render "leave_requests"%>
</div>
 <%= will_paginate @leaves %>
</div>
<% end %>