config/routes.rb
LeaveSystem::Application.routes.draw do
 
match '/employees/get_emp_manager_name/:id' => 'employees#get_emp_manager_name' 

match '/employees/emp_leave_status' => 'employees#emp_leave_status'

match '/articles/:id/save_comment' => 'articles#save_comment'

match '/employees/employee_separation' => 'employees#employee_separation' 
match '/leave_credits/:id/ohupdate' => 'leave_credits#ohupdate'

resource :authentication, :controller => "authentication" do
  member do
     match :login
     get :logout
     match :set_password
     match :forgot_password
     match :reset_password
  end
end

resources :holidays, :controller => 'holidays' do
  member do
      post 'destroy/id', :action => :destroy
  end
end

resources :employees, :controller => "employees" do
   member do
       put :update
       get :leave_balances
       get :my_leave_approvals
       get :my_leaves
       get :team_leaves   
	get :anew, :action => :anew
post :acreate, :action => :acreate
       post 'destroy/id', :action => :destroy
   end

   resources :leaves, :controller => "leaves" do
    member do

	post :update
       get :request_details
       post :action_leave
       get :quarterly_credits
    end

   end
end

resources :articles do
member do

post 'aindex', :action => :aindex
get 'anew/id', :action => :anew
post 'acreate/id', :action => :acreate
end
end 

resources :leaves, :controller => "leave_credits" do

    collection do
get :ohindex
get :ohnew
post :ohcreate
get :ohedit
       get :show
       get :quarterly_credits
       post :rt_qlc
       get :annual_credits
       post :rt_alc
    end
end

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :body, :author_emp_id, :title

validates_presence_of :title, :message => "title cannot be blank"
  validates_presence_of :body, :message => "body cannot be blank"
  validates_uniqueness_of :title, :message => "title should be unique"

  belongs_to :employee, :class_name => "Employee"
  has_many :comments, :dependent => :destroy

end

app/controllers/articles_controller.rb
require 'will_paginate/array'
class ArticlesController < ApplicationController
before_filter :login_required
before_filter :find_user_id
before_filter :find_logged_emp

layout 'article'

def new
    @article=Article.new
end

def index
    @articles=Article.all.paginate(:page => params[:page], :per_page => 10)
end

def create
    @article=Article.new(params[:article])
    @article.author_emp_id=@emp.emp_id
    @article.employee_id=@emp.id
    if @article.save
       flash[:notice]="Blog was saved successfully!"
       redirect_to :action => 'index'
    else

       flash[:errors]="Blog was not saved, #{@article.errors}"
       render :action => "new"
    end
end

def show
@article=Article.find(params[:id])
@comments = Comment.where('article_id =?', @article.id).order('id desc').to_a.paginate(:page => params[:page], :per_page => 5)
end

def aindex
end

def anew
@comment = Comment.new
@article=Article.find(params[:id])
@comments = Comment.where('article_id =?', @article.id).order('id desc').to_a.paginate(:page => params[:page], :per_page => 5)
@empname = @emp.first_name
end

def acreate
@article=Article.find(params[:id])
@comment = @article.comments.create(params[:data])
@comment.commenter_emp_id = @emp.emp_id
if @comment.save
 redirect_to :action =>'show'
end
end

def edit
   @article=Article.find(params[:id])
end

def update
    @article=Article.find(params[:id])
    @article.update_attributes(params[:article])
    if @article.save
       flash[:notice]="Blog was updated successfully!"
       redirect_to :action=>'show'
    else
       flash[:errors]="Blog could not be updated, #{@article.errors}"
       redirect_to :action=>'index'
    end
end

def destroy
    @article=Article.find(params[:id])
    if @article.destroy
       redirect_to :action=>'index'
    else
       flash[:errors]="There was an error deleting this blog post, #{@article.errors}"
       redirect_to :action=>'show'
    end
end


def save_comment
    #@article_id=params[:id]
    @article=Article.find(params[:id])
    @comment = Comment.new
    #@article.comments.create(params[:comment])
    @commentator = Employee.where('first_name=? AND last_name=?',params[:comment][:commentator_first_name],params[:comment][:commentator_last_name])[0]
    @comment.commenter_emp_id=@commentator.emp_id
    @comment.body=params[:comment][:body]
    @comment.article_id=params[:id]
    if @comment.save
        flash[:notice]="New comment was saved successfully!"
	redirect_to :action =>'show'
    else
        flash[:errors]="New comment could not be saved, please try again!, #{@comment.errors}"
        redirect_to :action => 'anew'
    end
end

def find_user_id
    @uid=current_user_id
end

def find_logged_emp
    @emp=current_emp
end

 
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_anew.html.erb
 <%= form_for :data, :url =>{:action => 'acreate', :id => @article.id } do |i| %>
&nbsp;&nbsp;&nbsp;&nbsp;<%= i.text_area :body, :cols => "25", :rows => "6", :limit => "250", :class => 'blog_comment_box' %>
<%#= i.submit 'save' %>
<% end %>

app/views/articles/anew.html.erb
 <% content_for(:page_title, "Blog details") %>
<% content_for :emp_sel do %>
<fieldset id="blog_body">
<h3><%=@article.title%></h3>
<div id="blog_text">
  <%=@article.body%><br/><br>
<span id="blog_author">Author: <%=Employee.find(@article.employee_id).first_name%> <%=Employee.find(@article.employee_id).last_name%></span><br/>
<span id="blog_date">Date: <%=@article.created_at.strftime('%d-%m-%y')%></span>
</div>
<div id="blog_actions">
<% if @article.author_emp_id==@emp.emp_id %>
     <%=link_to "Edit Blog Post", edit_article_path%>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
     <%=link_to "Delete Blog Post", article_path, :method => 'delete', :id => @article.id, :confirm => 'Are you sure you want to delete this blog post?'%>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<% end %>
     <%=link_to "Comment",:action => "anew"%>
</div>
<br/>
<%= render "anew" %>
<br/>
<div id="blog_comments">
     <h4>Comments</h4>
       <div id="blog_com">
	<% @comments.each do |comment| %>
 <span id="blog_commenter"><%= Employee.find_by_emp_id(comment.commenter_emp_id).first_name %> <%= Employee.find_by_emp_id(comment.commenter_emp_id).last_name %> says:</span><br>
            <div id="comment_body">
              <%= comment.body %><br><br>
            </div>
        <% end %>
        </div>
       <%= will_paginate @comments %>
</div>
</fieldset>
<% end %>

app/views/articles/edit.html.erb
<% content_for(:page_title, "Edit Blog") %>
<% content_for :emp_sel do %>
<h3>Edit Blog</h3>
<div id="blog_dtls">
<%=form_for @article, :url=>article_path(@article), :html => {:class=>'article_form'} do |f| %>
<div id="edit_emp_blog">
 <fieldset id="edit_emp_article">

    <label for="article_title">Title</label>
  <%= f.text_field :title, :size=>'35',:maxlength =>'250' %><br/><br/>

  <label for="article_body">Body</label>
  <%= f.text_area :body, :cols=>50,:rows =>10 %><br/><br/>
  
<div class="buttons">
	<input type="submit" name="commit" value="Update Blog" class="publish_button" tabindex="8"> 
</div>

</fieldset>
</div>
<% end %>
</div>
<% end %>

app/views/articles/index.html.erb
<% content_for(:page_title, "Blogs List") %>          
<% content_for :emp_sel do %>
<div id="emp_blogs_list">
<h3>RapidThink Blogs</h3>
   <table id="rt_blogs">
       <tbody>
          <tr>
             <th>Title</th>
             <th>Author</th>
             <th>Published Date</th>
         </tr>
<% @articles.each do |art| %>
        <tr>
           <td><%=link_to art.title,article_path(art.id)%></td>
           <td><%=Employee.find(art.employee_id).first_name%> <%=Employee.find(art.employee_id).last_name%></td>
           <td><%=art.created_at.strftime('%d-%m-%y')%></td>
        </tr>
<% end %>
   </tbody>
 </table>
<%=will_paginate @articles%>
<% end %>

app/views/articles/new.html.erb
<% content_for :emp_sel do %>
<%= form_for :article, :url => articles_path do |f| %>
<div id="new_emp_blog">
 <fieldset id="new_emp_article">
 <% content_for(:page_title, "New Blog")%>
<h3>New Blog</h3>
  <label for="article_title">Title</label>
  <%= f.text_field :title, :size=>'35',:maxlength =>'250', :class => "validate[required]" %><br/><br/>

  <label for="article_body">Body</label>
  <%= f.text_area :body, :cols=>50,:rows =>10, :class => "validate[required]" %><br/><br/>
  
<div class="buttons">
	<input type="submit" name="commit" value="Publish" class="publish_button" tabindex="8"> 
</div>

</fieldset>
</div>
<% end %>
<% end %>

app/views/articles/show.html.erb
 <% content_for(:page_title, "Blog details") %>
<% content_for :emp_sel do %>
<fieldset id="blog_body">
<h3><%=@article.title%></h3>
<div id="blog_text">
  <%=@article.body%><br/><br>
<span id="blog_author">Author: <%=Employee.find(@article.employee_id).first_name%> <%=Employee.find(@article.employee_id).last_name%></span><br/>
<span id="blog_date">Date: <%=@article.created_at.strftime('%d-%m-%y')%></span>
</div>
<div id="blog_actions">
<% if @article.author_emp_id==@emp.emp_id %>
     <%=link_to "Edit Blog Post", edit_article_path%>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
     <%=link_to "Delete Blog Post", article_path, :method => 'delete', :id => @article.id, :confirm => 'Are you sure you want to delete this blog post?'%>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<% end %>
     <%=link_to "Comment",:action => "anew"%>
</div>
<div id="blog_comments">
     <h4>Comments</h4>
       <div id="blog_com">
	<% @comments.each do |comment| %>
	 <span id="blog_commenter"><%= Employee.find(:all, :conditions=>{:emp_id => comment.commenter_emp_id}, :select => :first_name)[0].first_name
 %> says:</span><br>
            <div id="comment_body">
              <%= comment.body %><br><br>
            </div>
        <% end %>
        </div>
       <%= will_paginate @comments %>
</div>
</fieldset>
<% end %>