config/routes.rb
LeaveSystem::Application.routes.draw do
 
match '/employees/get_emp_manager_name/:id' => 'employees#get_emp_manager_name' 

match '/employees/emp_leave_status' => 'employees#emp_leave_status'

match '/articles/:id/save_comment' => 'articles#save_comment'

match '/employees/employee_separation' => 'employees#employee_separation' 
match '/leave_credits/:id/ohupdate' => 'leave_credits#ohupdate'

resource :authentication, :controller => "authentication" do
  member do
     match :login
     get :logout
     match :set_password
     match :forgot_password
     match :reset_password
  end
end

resources :holidays, :controller => 'holidays' do
  member do
      post 'destroy/id', :action => :destroy
  end
end

resources :employees, :controller => "employees" do
   member do
       put :update
       get :leave_balances
       get :my_leave_approvals
       get :my_leaves
       get :team_leaves   
	get :anew, :action => :anew
post :acreate, :action => :acreate
       post 'destroy/id', :action => :destroy
   end

   resources :leaves, :controller => "leaves" do
    member do

	post :update
       get :request_details
       post :action_leave
       get :quarterly_credits
    end

   end
end

resources :articles do
member do

post 'aindex', :action => :aindex
get 'anew/id', :action => :anew
post 'acreate/id', :action => :acreate
end
end 

resources :leaves, :controller => "leave_credits" do

    collection do
get :ohindex
get :ohnew
post :ohcreate
get :ohedit
       get :show
       get :quarterly_credits
       post :rt_qlc
       get :annual_credits
       post :rt_alc
    end
end

end

app/models/leave.rb
class Leave < ActiveRecord::Base
  attr_accessible :action_remarks, :admin_comments, :approver_emp_id, :end_date, :ref_id, :leave_type, :no_of_days,
  :requester_emp_id, :start_date, :status, :request_remarks, :request_date, :status

validate :end_date_grt_than_start_date, :if => Proc.new{|a| a.status=="New"}
validates_presence_of :requester_emp_id
validates_presence_of :leave_type
validates_presence_of :start_date, :end_date, :no_of_days
validates_presence_of :status
validates_presence_of :request_remarks, :if => Proc.new{ |a| a.status=="New" }, :message => "Please input request remarks"



#validates_numericality_of :requester_emp_id, :only_integer => true, :message => "Please input a valid entry for requester emp id"
#validates_numericality_of :approver_emp_id, :only_integer => true, :message => "Please enter a whole number for approver emp id"
validates_numericality_of :no_of_days, :only_integer => true, :message => "Please enter a whole no for no. of days of leave"
validates_date :start_date, :end_date

belongs_to :employee, :class_name => 'Employee', :foreign_key => 'employee_id'

def self.search_leaves(search)
   if search
	search = search.split(' ').first
	search = Employee.where('first_name =?',search).pluck(:emp_id) 
       where('ref_id LIKE? or requester_emp_id LIKE?', "%#{search}%", "%#{search}%")
       #ActiveRecord::Base.logger.info("Ticket: #{s.to_s}")
    
   else
       scoped
   end
end



def is_new?
   self.status=='New'
end

def is_actioned?
    self.status!='New'
end

def end_date_grt_than_start_date
     errors.add(:start_date,"Leave end date should be greater than or equal to Leave start date") if 
     (!no_of_days.blank? and no_of_days <= 0) 
end



end

app/controllers/leaves_controller.rb
require 'will_paginate/array'
class LeavesController < ApplicationController
before_filter :login_required
before_filter :find_user_id
before_filter :find_logged_emp

layout 'leave'

def new
 @leave=Leave.new
 Rails.logger.info("First name of current user is: #{@emp.first_name}")
end

def create
 @leave=Leave.new(params[:leave])
 @leave.end_date = @leave.end_date.strftime("%d-%b-%Y")
 @leave.start_date = @leave.start_date.strftime("%d-%b-%Y")
 @leave.no_of_days = (@leave.end_date - @leave.start_date).to_i + 1
 
 @holiday_date = Holiday.find(:all, :conditions => {:holiday_type =>"Holiday"}, :select => :holiday_date)

@optional_holiday_date = Holiday.find(:all, :conditions => {:holiday_type => "Optional Holiday"}, :select=>:holiday_date)
      Rails.logger.info("The enddate Debit is: #{@leave.end_date}")
      Rails.logger.info("The startdate Debit is: #{@leave.start_date}")
  y = x = 0
    s = Array.new
    t = Array.new
    k = @leave.no_of_days
    i =  @holiday_date.count
    m =  @optional_holiday_date.count
    a = @leave.start_date
    b = @leave.end_date
   for j in 1..k            # if Holiday present no_of_days count should not to be considered
      for h in 0...i
        s[h] = @holiday_date[h].holiday_date
          if a == s[h] 
            x = x + 1 
	  end
      end

      for n in 0...m
          t[n] =  @optional_holiday_date[n].holiday_date
	if a == t[n] 
            y = y + 1
         oh_date = t[n]  
	  end
 	end
 
      if a.strftime("%a") == "Sun"        # if sunday no_of_days count should not to be considered
         x = x + 1 
      end
      if a.strftime("%a") == "Sat"        # if saturday no_of_days count should not to be considered
         x = x + 1
      end 
      a = a + 1
   end

 @leave.no_of_days = @leave.no_of_days - x - y    # x the no of "holiday, optional holiday, sunday and saturday" count
 @leave.requester_emp_id=@emp.emp_id
 @leave.employee_id=@emp.id
 lt=params[:leave][:leave_type]
 lref_id=@leave.ref_id=("LR" + lt.to_s + rand(10 ** 10).to_s.rjust(10,'0')).to_s
 @leave.approver_emp_id=@emp.find_leave_approver.emp_id

	
   if @leave.leave_type == "SL" # if sick leave balance is zero, user cannt apply sick leave
      @leavecredit_sl = Leave.find(:all, :conditions => {:requester_emp_id => @emp.emp_id, :leave_type => "SL", :status => "Credit"}, :select => "SUM(no_of_days) AS no_of_days", :group => { :requester_emp_id => @emp.emp_id})
      Rails.logger.info("The SL Credit is: #{@leavecredit_sl}")
      @leavedebit_sl = Leave.find(:all, :conditions => {:requester_emp_id => @emp.emp_id, :leave_type => "SL", :status => "Approved"}, :select => "SUM(no_of_days) AS no_of_days", :group => { :requester_emp_id => @emp.emp_id})
      Rails.logger.info("The SL Debit is: #{@leavedebit_sl}")
    if @leavedebit_sl == []
     @sickleavebal = @leavecredit_sl[0].no_of_days
   else
    @sickleavebal = @leavecredit_sl[0].no_of_days  - @leavedebit_sl[0].no_of_days
   end
      if @sickleavebal == 0 || (@sickleavebal - @leave.no_of_days) < 0
        flash[:notice]="You don't have enough Sick Leave balance to apply"
        render :action => "new"
      else
        if @leave.save
         Notifications.leavereq(@emp).deliver
          flash[:notice]="Leave request #{lref_id} was submitted successfully!"
        else
       flash[:errors]="Leave request action was not successful, #{@leave.errors}"
        end
        redirect_to :action => 'new'
      end
   elsif @leave.leave_type == "CL" # if casual leave balance is zero, user cannt apply casual leave
      @leavecredit_cl = Leave.find(:all, :conditions => {:requester_emp_id => @emp.emp_id, :leave_type => "CL", :status => "Credit"}, :select => "SUM(no_of_days) AS no_of_days", :group => { :requester_emp_id => @emp.emp_id})
@leavedebit_cl = Leave.find(:all, :conditions => {:requester_emp_id => @emp.emp_id, :leave_type => "CL", :status => "Approved"}, :select => "SUM(no_of_days) AS no_of_days", :group => { :requester_emp_id => @emp.emp_id})
	if @leavedebit_cl == []
 	  @casualleavebal = @leavecredit_cl[0].no_of_days
	else
      @casualleavebal = @leavecredit_cl[0].no_of_days - @leavedebit_cl[0].no_of_days
	end
      if @casualleave == 0 || (@casualleavebal - @leave.no_of_days) < 0
        flash[:notice]="You don't have enough Casual Leave balance to apply"
        render :action => "new"
      else
        if @leave.save
         Notifications.leavereq(@emp).deliver
          flash[:notice]="Leave request #{lref_id} was submitted successfully!"
        else
       flash[:errors]="Leave request action was not successful, #{@leave.errors}"
        end
        redirect_to :action => 'new'
      end
   elsif @leave.leave_type == "OH" # if optional leave balance is zero, user cannt apply optional leave
   x = Time.now.year
 	 a= Date.new(x)
	
	 z = x + 1
	 b = Date.new(x).change(:year => z) -1
	@leavecredit_oh = Leave.find(:all, :conditions => {:requester_emp_id => @emp.emp_id, :leave_type => "OH", :status => "Credit", :start_date => a..b }, :select => "SUM(no_of_days) AS no_of_days", :group => { :requester_emp_id => @emp.emp_id})
	
	 b = Date.new(x).change(:year => z) 
	@leavedebit_oh = Leave.find(:all, :conditions => {:requester_emp_id => @emp.emp_id, :leave_type => "OH", :status => "Approved", :start_date => a..b }, :select => "SUM(no_of_days) AS no_of_days", :group => { :requester_emp_id => @emp.emp_id})
		
	if @leavecredit_oh == [] && @leavedebit_oh == [] 
           @optionalholidaybal = 0
        elsif @leavedebit_oh == [] 
	   @optionalholidaybal = @leavecredit_oh[0].no_of_days
	else
        @optionalholidaybal = @leavecredit_oh[0].no_of_days - @leavedebit_oh[0].no_of_days
	end
        if @optionalholidaybal == 0 || (@optionalholidaybal - @leave.no_of_days) < 0
        flash[:notice]="You don't have enough Optional Holidays to apply"
        render :action => "new"
      else
      Rails.logger.info("The opt leave: #{y}")
        if y > 0
 @leave.no_of_days = y  

      Rails.logger.info("The enddate Debit is: #{@leave.end_date}")
     Rails.logger.info("The enddate Debit is: #{@leave.start_date}")
        if @leave.save
         Notifications.leavereq(@emp).deliver
          flash[:notice]="Leave request #{lref_id} was submitted successfully!"
        else
          flash[:notice]="Request_remarks not to be blank"
        end
	else
           flash[:notice]="Hi The date you are entered is not an optional holiday"
       end
        redirect_to :action => 'new'
   
      end
   elsif @leave.leave_type == "EL" # if earned leave balance is zero, user cannt apply earned leave
      @leavecredit_el = Leave.find(:all, :conditions => {:requester_emp_id => @emp.emp_id, :leave_type => "EL", :status => "Credit"}, :select => "SUM(no_of_days) AS no_of_days", :group => { :requester_emp_id => @emp.emp_id})
@leavedebit_el = Leave.find(:all, :conditions => {:requester_emp_id => @emp.emp_id, :leave_type => "EL", :status => "Approved"}, :select => "SUM(no_of_days) AS no_of_days", :group => { :requester_emp_id => @emp.emp_id})
	if @leavedebit_el == []
      @earnedleavebal = @leavecredit_el[0].no_of_days
	else
      @earnedleavebal = @leavecredit_el[0].no_of_days - @leavedebit_el[0].no_of_days
	end
      if @earnedleavebal == 0 || (@earnedleavebal - @leave.no_of_days) < 0
        flash[:notice]="Hi You don't have enough Earned leave to apply"
        render :action => "new"
      else
        if @leave.save
         Notifications.leavereq(@emp).deliver
          flash[:notice]="Leave request #{lref_id} was submitted successfully!"
        else
       flash[:errors]="Leave request action was not successful, #{@leave.errors}"
        end
        redirect_to :action => 'new'
      end
   end

if y > 0 && @leave.leave_type != "OH"
	 @opt_leave = Leave.new
	 @opt_leave.end_date = oh_date.strftime("%d-%b-%Y")
         @opt_leave.start_date = oh_date.strftime("%d-%b-%Y")
         @opt_leave.requester_emp_id=@emp.emp_id
         @opt_leave.employee_id=@emp.id
	 @opt_leave.no_of_days = y
	 @opt_leave.leave_type= "OH"
	 @opt_leave.request_date = Date.today
	 @opt_leave.request_remarks = @leave.request_remarks
         lref_id=@opt_leave.ref_id=("LR" + lt.to_s + rand(10 ** 10).to_s.rjust(10,'0')).to_s
         @opt_leave.approver_emp_id=@emp.find_leave_approver.emp_id
         @opt_leave.status = 'New'
          x = Time.now.year
 	 a= Date.new(x)
	
	 z = x + 1
	 b = Date.new(x).change(:year => z) -1
	@leavecredit_oh = Leave.find(:all, :conditions => {:requester_emp_id => @emp.emp_id, :leave_type => "OH", :status => "Credit", :start_date => a..b }, :select => "SUM(no_of_days) AS no_of_days", :group => { :requester_emp_id => @emp.emp_id})
@leavedebit_oh = Leave.find(:all, :conditions => {:requester_emp_id => @emp.emp_id, :leave_type => "OH", :status => "Approved"}, :select => "SUM(no_of_days) AS no_of_days", :group => { :requester_emp_id => @emp.emp_id})
   	  if @leavecredit_oh == [] && @leavedebit_oh == [] 
            @optionalholidaybal = 0
          elsif @leavedebit_oh == [] 
	    @optionalholidaybal = @leavecredit_oh[0].no_of_days
     	  else
            @optionalholidaybal = @leavecredit_oh[0].no_of_days - @leavedebit_oh[0].no_of_days
   	  end
      
  	  if @optionalholidaybal == 0 
             flash[:notice]="You don't have enough Optional Holidays to apply"
          else
      Rails.logger.info("The enddate Debit is: #{@opt_leave.end_date}")
      Rails.logger.info("The enddate Debit is: #{@opt_leave.start_date}")
             if @opt_leave.save
         Notifications.leavereq(@emp).deliver
              flash[:notice]="Leave request #{lref_id} was submitted successfully!"
             else
       flash[:errors]="Leave request action was not successful, #{@leave.errors}"
             end
	  end
	end
 


end

def edit
    @leave=Leave.find(params[:id]) 

end

def update
    @leave=Leave.find(params[:id]) 
    @leave.action_date = Time.now
       if @leave.update_attributes(params[:leave])
          redirect_to :action => 'request_details'

app/helpers/leaves_helper.rb
module LeavesHelper
end

app/views/leaves/_leaves.html.erb
<% content_for(:page_title, "Leave Request Details") %>
<% content_for :emp_sel do %>
  <h3>Leave Request Details</h3>

<% if @leave.is_new? && @leave.requester_emp_id!=@emp.emp_id %>
<div id="lv_dtl">
  <%=form_for :leave, :url=>action_leave_employee_leafe_path, :html => {:class => "leave_apprvl_form"} do |f|%>
   <fieldset id="lv_req_dtl">
        <div id="emp_req_dtls">
          <label for="leave_req_id">Ref Id:</label>
          <span class="emp_lv_dt"><%=@leave.ref_id%></span><br/><br/>
          <label for="employee_name">Requester:</label>
          <span class="emp_lv_dt"><%=@leave.employee.first_name%> <%=@leave.employee.last_name%></span><br/></br>
          <label for="employee_name">Manager:</label>
          <span class="emp_lv_dt"><%=Employee.find_by_emp_id(@leave.employee.manager_emp_id).first_name%> <%=Employee.find_by_emp_id(@leave.employee.manager_emp_id).last_name%></span><br/></br>
          <label for="leave_type">Leave Type:</label>
          <span class="emp_lv_dt"><%=@leave.leave_type%></span><br/><br/>
          <label for="leave_start_date">Start Date:</label>
          <span class="emp_lv_dt"><%=@leave.start_date.strftime('%a, %d-%b-%Y')%></span><br/><br/>
          <label for="leave_end_date">End Date:</label>
          <span class="emp_lv_dt"><%=@leave.end_date.strftime('%a, %d-%b-%Y')%></span><br/><br/>
          <label for="no_of_days">No. of days:</label>
          <span class="emp_lv_dt"><%=@leave.no_of_days%></span><br/><br/>
          <label for="request_remarks">Request Remarks:</label>
          <span class="emp_lv_dt"><%=@leave.request_remarks%></span><br/><br/>
          <label for="leave_request_date">Request Date:</label>
          <span class="emp_lv_dt"><%=@leave.request_date.strftime('%a, %d-%b-%Y')%></span><br/><br/><br/>
          <label for="employee_name">Leave Request Approver:</label>
          <span class="emp_lv_dt"><%=@leave.employee.find_leave_approver.first_name%> <%=@leave.employee.find_leave_approver.last_name%></span><br/></br>
          <label for="status">Action:</label>
          <%=f.select :status, options_for_select([['Approve','Approved'],['Reject','Rejected'],['Reapply','Reapply']]) %><br/><br/>
          <label for="action_remarks">Action Remarks:</label>
          <%=f.text_area :action_remarks, :cols=>13, :rows=>4 %><br/><br/>
          <%=f.hidden_field :requester_emp_id, :value => @leave.requester_emp_id %>
          <%=f.hidden_field :action_date%>
          <%=f.hidden_field :id, :value => @leave.id %>

      </div>
      <div class="submit">
          <%= f.submit 'Action', :class => 'leave_action_button' %>
     </div>

    </fieldset>
  <% end %>
</div>

<% else %>
      <div id="lv_dtl">
     <fieldset id="lv_req_dtl">
         <div id="emp_req_dtls">
          <label for="leave_req_id">Ref Id:</label>
          <span class="emp_lv_dt"><%=@leave.ref_id%></span><br/><br/>
          <label for="employee_name">Requester:</label>
          <span class="emp_lv_dt"><%=@leave.employee.first_name%> <%=@leave.employee.last_name%></span><br/></br>
          <label for="employee_name">Manager:</label>
          <span class="emp_lv_dt"><%=Employee.find_by_emp_id(@leave.employee.manager_emp_id).first_name%> <%=Employee.find_by_emp_id(@leave.employee.manager_emp_id).last_name%></span><br/></br>
          <label for="leave_type">Leave Type:</label>
          <span class="emp_lv_dt"><%=@leave.leave_type%></span><br/><br/>
          <label for="leave_start_date">Start Date:</label>
          <span class="emp_lv_dt"><%=@leave.start_date.strftime('%a, %d-%b-%Y')%></span><br/><br/>
          <label for="leave_end_date">End Date:</label>
          <span class="emp_lv_dt"><%=@leave.end_date.strftime('%a, %d-%b-%Y')%></span><br/><br/>
          <label for="no_of_days">No. of leave days:</label>
          <span class="emp_lv_dt"><%=@leave.no_of_days%></span><br/><br/>
          <label for="request_remarks">Request Remarks:</label>
          <span class="emp_lv_dt"><%=@leave.request_remarks%></span><br/><br/>
          <label for="leave_request_date">Request Date:</label>
          <span class="emp_lv_dt"><%=@leave.request_date.strftime('%a, %d-%b-%Y')%></span><br/><br/><br/>
          <label for="employee_name">Leave Request Approver:</label>
          <span class="emp_lv_dt"><%=@leave.employee.find_leave_approver.first_name%> <%=@leave.employee.find_leave_approver.last_name%></span><br/></br>
          <label for="status">Status:</label>
          <% if !@leave.is_new? %>
             <span class="emp_lv_dt"><%=@leave.status%></span><br/><br/>
              <label for="action">Action Date:</label>
              <span class="emp_lv_dt"><%=@leave.action_date.strftime('%a, %d-%b-%Y')%></span><br/><br/>
              <label for="action_remarks">Action Remarks:</label>
              <span class="emp_lv_dt"><%=@leave.action_remarks%></span><br/><br/>
          <% else %> 
             <span class="emp_lv_dt_tba">TO BE ACTIONED</span><br/><br/>
          <% end %>
         
      </div>
   </fieldset>
   </div>

<% end %>

<% end %>

app/views/leaves/_new_leave_details.html.erb
<%= form_for :leave, :url => employee_leaves_path  do |f| %>
<fieldset id="leave_req">
<label for="leave_start_date">Leave Start Date </label>
<%= f.date_select :start_date, :default => Date.today, :order => [:day, :month, :year], :use_short_month => true, :start_year => (Date.today.year), :end_year => (Date.today.year + 1) %><br/><br/>

<label for="leave_end_date", id = "leave_end_label">Leave End Date</label>
<%= f.date_select :end_date,  :default => Date.today, :order => [:day, :month, :year], :use_short_month => true, :start_year => (Date.today.year), :end_year => (Date.today.year + 1), :html => {:class => "leave_end"}  %><br/><br/>

   <label for="same_as_local_addr">Leave as one day</label>
  <input id="copy_date" name="copy_date" type="checkbox" value="0"/><br><br/>

<label for="leave_type">Leave Type</label>
<%= f.select :leave_type, options_for_select([["Sick Leave", "SL"], ["Casual Leave", "CL"],["Earned Leave", "EL"], ["Optional Holiday", "OH"]]) %><br/><br/>

<label for="request_remarks">Request Remarks</label>
<center><%= f.text_area :request_remarks, :cols => "50", :rows => "6" %><br/><br/></center>

<%=f.hidden_field :status, :value => 'New' %> 
<%=f.hidden_field :request_date, :value => Date.today%>


<div class="submit">
   <%= f.submit 'Request Leave', :class => 'leave_button' %>
</div>
</fieldset>

<% end %>

app/views/leaves/_quarterlyleavecredit_details.html.erb
<%= form_for :qlc, :url => {:action => 'rt_qlc'}, :emp_id => @emp_id do |f| %>
    <%= f.hidden_field :start_date, :value => Time.now.strftime("%d-%b-%Y")%>
    <%= f.hidden_field :end_date, :value => Time.now.strftime("%d-%b-%Y")%>
    <%= f.hidden_field :leave_type, :value => "Earned leave"%>
    <%= f.hidden_field :admin_comments, :value => "Quarterly Credit"%>
    <%= f.hidden_field :no_of_days, :value => 3%>
<div class="actions">
   <%= f.submit 'Quarterly leave credit', :confirm => 'Are you sure to credit?'  %>
</div>
<% end %>

app/views/leaves/edit.html.erb
<% content_for(:page_title, "New Leave Request") %>
<% content_for :emp_sel do %>
<div id="emp_leave_request">
<fieldset id="leave_req">
<%= form_for :leave, :url => {:action => 'update', :id =>@leave.id }  do |f| -%>
 

<label for="leave_start_date">Leave Start Date </label>
<%= f.date_select :start_date, :default => Date.today, :order => [:day, :month, :year], :use_short_month => true, :start_year => (Date.today.year), :end_year => (Date.today.year + 1) %><br/><br/>

<label for="leave_end_date">Leave End Date</label>
<%= f.date_select :end_date, :default => Date.today, :order => [:day, :month, :year], :use_short_month => true, :start_year => (Date.today.year), :end_year => (Date.today.year + 1) %><br/><br/>

<label for="leave_type">Leave Type</label>
<%= f.select :leave_type, options_for_select([["Sick Leave", "SL"], ["Casual Leave", "CL"],["Earned Leave", "EL"], ["Optional Holiday", "OH"]]) %><br/><br/>

<label for="request_remarks">Request Remarks</label>
<center><%= f.text_area :request_remarks, :cols => "50", :rows => "6" %><br/><br/></center><br/><br/>

<%=f.hidden_field :status, :value => 'Withdrawn' %> 
<%#=f.hidden_field :action_date, :value => Date.today.strftime('%a, %d-%b-%Y') %> 
<%=f.hidden_field :request_date, :value => Date.today%>


<div class="submit">
   <%= f.submit 'cancel leavereq', :confirm => "Are you sure to delete request", :class => 'leave_button' %>
</div>

<% end %>
</fieldset>
</div>
<% end %>

app/views/leaves/index.html.erb
<% content_for(:page_title, "View Employees") -%>
<% content_for :emp_sel do %>
<div id="rt_emps">
<% if @emp.is_admin? %>
<h3>Leaves </h3>

<%= render :partial => "leaves", :object => @emp %>
<%= will_paginate @employees %>
<% else %>
<h3>My Team</h3>
<%= render :partial => "leaves", :object => @emp %>
<%= will_paginate @employees %>
<% end %>
</div>
<% end %>

app/views/leaves/my_leaves.html.erb
<% content_for(:page_title, "My Leave History") %>
<% content_for :emp_sel do %>
<div id="my_leaves">
  <h3>My Leave History</h3>
<div id="my_leave_reqs">
   <%=render "leave_requests"%>
</div>
 <%= will_paginate @leaves %>
</div>
<% end %>

app/views/leaves/new.html.erb
<% content_for(:page_title, "New Leave Request") %>
<% content_for :emp_sel do %>
<h3>New Leave Request</h3>
<div id="emp_leave_request">
  <%= render "new_leave_details" %>
</div>
<% end %>

app/views/leaves/quarterly_credits.html.erb
<% content_for(:page_title, "Quarterly RT Leave Credits ") %>
<% content_for :emp_sel do %>
<div id="emp_qlc">
   <%= render 'quarterlyleavecredit_details' %>
</div>
<% end %>