config/routes.rb
LeaveSystem::Application.routes.draw do
 
match '/employees/get_emp_manager_name/:id' => 'employees#get_emp_manager_name' 

match '/employees/emp_leave_status' => 'employees#emp_leave_status'

match '/articles/:id/save_comment' => 'articles#save_comment'

match '/employees/employee_separation' => 'employees#employee_separation' 
match '/leave_credits/:id/ohupdate' => 'leave_credits#ohupdate'

resource :authentication, :controller => "authentication" do
  member do
     match :login
     get :logout
     match :set_password
     match :forgot_password
     match :reset_password
  end
end

resources :holidays, :controller => 'holidays' do
  member do
      post 'destroy/id', :action => :destroy
  end
end

resources :employees, :controller => "employees" do
   member do
       put :update
       get :leave_balances
       get :my_leave_approvals
       get :my_leaves
       get :team_leaves   
	get :anew, :action => :anew
post :acreate, :action => :acreate
       post 'destroy/id', :action => :destroy
   end

   resources :leaves, :controller => "leaves" do
    member do

	post :update
       get :request_details
       post :action_leave
       get :quarterly_credits
    end

   end
end

resources :articles do
member do

post 'aindex', :action => :aindex
get 'anew/id', :action => :anew
post 'acreate/id', :action => :acreate
end
end 

resources :leaves, :controller => "leave_credits" do

    collection do
get :ohindex
get :ohnew
post :ohcreate
get :ohedit
       get :show
       get :quarterly_credits
       post :rt_qlc
       get :annual_credits
       post :rt_alc
    end
end

end

app/views/layouts/_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LeaveSystem</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="page">
  <div id="header">
     <div id="bannerimg">
       <a href="http://www.rapidthink.com" target="_blank"><%= image_tag "/images/app_header1.gif", :alt => "Rapidthink Software Pvt Ltd.", :class => "sys_banner" %></a>
     </div>
  </div>
<div id="main">
    <div id="primary">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </div>
</div>
<%= render :partial => "/shared/notices" %>
</body>
</html>

app/views/layouts/_emp_hub.html.erb
<% content_for :content do -%>
<div id="outer">
<div class="left_col">
      <div id="emp_home">
         <%= yield :emp_home %>
     </div>
</div>

<div class="right_col">
  <div id="logout"><%= link_to("Logout", logout_authentication_path, :confirm => "Are You Sure to Logout?") %></div>
  <span id="welcome">Welcome</span>&nbsp;<span id="ols_user"><%=@emp.first_name.capitalize%> <%=@emp.last_name.capitalize%></span>
  <div align = "right"><div id="reset"><%=link_to("Reset Password", reset_password_authentication_path) %></div> </div>  

   <% if content_for? :emp_sel %>
    <div id="menu_sel">
      <%= yield :emp_sel %>
    </div>
   <% end %>

 </div>

</div>

<% end %>

<%= render :file => 'layouts/_application' %>

app/views/layouts/article.html.erb
<% content_for :article_content do %>
   <div id="article">
       <%= yield %>
   </div>
<% end %>
<%= render :partial => "/employees/emp_home"%>

app/views/layouts/authentication.html.erb
<%= render :file => 'layouts/_application' %>

app/views/layouts/employee.html.erb
<% content_for :employee_content do %>
   <div id="employee">
       <%= yield %>
   </div>
<% end %>
<%= render :partial => "/employees/emp_home"%>
    

app/views/layouts/holiday.html.erb
<% content_for :holiday_content do %>
   <div id="holiday">
       <%= yield %>
   </div>
<% end %>
<%= render :partial => "/employees/emp_home"%>

app/views/layouts/leave.html.erb
<%= render :partial => "/employees/emp_home", :locals => {:object => @emp}%>
    